//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class associationtypesinassociation
    {
        public int Id { get; set; }
        public int Associations_Id { get; set; }
        public int AssociationTypes_Id { get; set; }
    
        public virtual associations associations { get; set; }
        public virtual associationtypes associationtypes { get; set; }
    }
}
