//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class associationtypes
    {
        public associationtypes()
        {
            this.associationtypesinassociation = new HashSet<associationtypesinassociation>();
            this.associationtypesinevents = new HashSet<associationtypesinevents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<associationtypesinassociation> associationtypesinassociation { get; set; }
        public virtual ICollection<associationtypesinevents> associationtypesinevents { get; set; }
    }
}
