//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public Association()
        {
            this.WebPage = new HashSet<WebPage>();
            this.TermSet = new HashSet<TermSet>();
        }
    
        public int Id { get; set; }
        public int CommunityId { get; set; }
        public int ParentAssociationId { get; set; }
        public int PublishingTermSetId { get; set; }
        public Nullable<int> AssociationType { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual ICollection<WebPage> WebPage { get; set; }
        public virtual ICollection<TermSet> TermSet { get; set; }
    }
}
