//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories
    {
        public categories()
        {
            this.categoriesinassociations = new HashSet<categoriesinassociations>();
            this.subcategories = new HashSet<subcategories>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<categoriesinassociations> categoriesinassociations { get; set; }
        public virtual ICollection<subcategories> subcategories { get; set; }
    }
}
