//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class community_permissions
    {
        public int Id { get; set; }
        public int users_Id { get; set; }
        public int communities_Id { get; set; }
        public string Role { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual communities communities { get; set; }
        public virtual users users { get; set; }
    }
}
