//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.WebPage = new HashSet<WebPage>();
            this.Component = new HashSet<Component>();
            this.ContentLayout = new HashSet<ContentLayout>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<WebPage> WebPage { get; set; }
        public virtual ICollection<Component> Component { get; set; }
        public virtual ICollection<ContentLayout> ContentLayout { get; set; }
    }
}
