//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public Feed()
        {
            this.Event = new HashSet<Event>();
            this.Term = new HashSet<Term>();
        }
    
        public int Id { get; set; }
        public string Mode { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Term> Term { get; set; }
    }
}
