//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation
    {
        public Navigation()
        {
            this.Link = new HashSet<Link>();
        }
    
        public int Id { get; set; }
        public int PublishingTermSetId { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual ICollection<Link> Link { get; set; }
    }
}
