//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomy
    {
        public Taxonomy()
        {
            this.TermSet = new HashSet<TermSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Created { get; set; }
        public string IsDeleted { get; set; }
    
        public virtual ICollection<TermSet> TermSet { get; set; }
    }
}
