//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.associations = new HashSet<associations>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<associations> associations { get; set; }
    }
}
