//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages
    {
        public webpages()
        {
            this.components = new HashSet<components>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public Nullable<int> AssociationId { get; set; }
        public string Layout { get; set; }
        public string Style { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LatestUpdate { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<components> components { get; set; }
    }
}
