//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem.Admin {
    
    
    public partial class PageSettings {
        
        /// <summary>
        /// PageManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EventHandlingSystem.PageSettingsControls.PageManager PageManager;
        
        /// <summary>
        /// RolePermManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EventHandlingSystem.PageSettingsControls.RolesPermissionsManager RolePermManager;
    }
}
