//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class communities
    {
        public communities()
        {
            this.associations = new HashSet<associations>();
            this.communitiesinevents = new HashSet<communitiesinevents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LatestUpdate { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<associations> associations { get; set; }
        public virtual ICollection<communitiesinevents> communitiesinevents { get; set; }
    }
}
