//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Term = new HashSet<Term>();
            this.Calendar = new HashSet<Calendar>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Summary { get; set; }
        public string Other { get; set; }
        public string Location { get; set; }
        public string ImageUrl { get; set; }
        public bool DayEvent { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string TargetGroup { get; set; }
        public long ApproximateAttendees { get; set; }
        public int AssociationId { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Term> Term { get; set; }
        public virtual ICollection<Calendar> Calendar { get; set; }
    }
}
