//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class filterdata
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Data { get; set; }
        public bool IsDeleted { get; set; }
        public int Components_Id { get; set; }
    
        public virtual components components { get; set; }
    }
}
