//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Id { get; set; }
        public int NavigationId { get; set; }
        public int TermId { get; set; }
        public string Url { get; set; }
        public Nullable<int> ParentLinkId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Navigation Navigation { get; set; }
    }
}
