//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class subeventtypes
    {
        public subeventtypes()
        {
            this.subeventtypesinevents = new HashSet<subeventtypesinevents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public int EventTypes_Id { get; set; }
    
        public virtual eventtypes eventtypes { get; set; }
        public virtual ICollection<subeventtypesinevents> subeventtypesinevents { get; set; }
    }
}
