//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.TermSet = new HashSet<TermSet>();
            this.Event = new HashSet<Event>();
            this.Calendar = new HashSet<Calendar>();
            this.Feed = new HashSet<Feed>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<TermSet> TermSet { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Calendar> Calendar { get; set; }
        public virtual ICollection<Feed> Feed { get; set; }
    }
}
