//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHandlingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        public int Id { get; set; }
        public string LogoUrl { get; set; }
        public string NavigationComponentId { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Community Community { get; set; }
        public virtual Association Association { get; set; }
    }
}
